import { useMemo, useState } from 'react';
import { ChevronRight, Compass, Eye, HelpCircle, Map, Pause, Play, RotateCcw, Sparkles, Star } from 'lucide-react';
import { candidates, COORDS, DIRECTOR_OUTCOMES, RELATIONS, recordTraversal, resumeState, storyBeat, WORDS } from './state.js';

const starters = [['勇敢','yǒng gǎn','brave','✦',true],['地图','dì tú','map','⌁',false],['闪电','shǎn diàn','lightning','ϟ',false],['秘密','mì mì','secret','◐',false],['迷路','mí lù','get lost','↝',false]];
const themes = [['雾林谜踪','Fog Forest Mystery',true],['太空失联','Lost in Space',false],['校园密室','Locked Room at School',false]];
const courageAnchors = ['勇敢','英勇','勇猛','胆怯'];
const mapAnchors = ['地图','线索','神秘线索'];
const courageRegion = ['勇敢','英勇','勇猛','胆怯','无畏','大胆','怯懦','胆小'];
const mapRegion = ['地图','路线','方向','地点','线索','路径','道路','旅程','北方','前方','出口','山谷','河流','营地','证据','谜题','秘密','寻找线索','发现线索','重要线索','神秘线索'];

function WordNode({ word, status='inactive', onClick, compact=false, anchor=false, story=false }) {
  const data = WORDS[word] || ['', ''];
  const actualStatus = story ? 'active story word' : status;
  const content = <>{anchor && <Star className="node-star" size={15} fill="currentColor"/>}<span className="hanzi">{word}</span><span className="pinyin">{data[0]}</span><span className="gloss">{data[1]}</span></>;
  const className = `word-node ${status} ${compact?'compact':''} ${anchor?'anchor':''} ${story?'story-word':''}`;
  return onClick
    ? <button className={className} onClick={onClick} aria-label={`${word}, ${data[1]}, ${actualStatus}`}>{content}</button>
    : <div className={className} aria-label={`${word}, ${data[1]}, ${actualStatus}`}>{content}</div>;
}

function EdgeLayer({ history=[], available=[], current, narrative=[] }) {
  const line = (from,to,key,className,label) => { const a=COORDS[from], b=COORDS[to]; if(!a||!b)return null; return <line key={key} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className={className} aria-label={label}/>; };
  return <svg className="truth-edges" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Word paths">
    {history.map(e=>line(e.from,e.to,`h-${e.order}`,`edge traversed relation-${e.relation}`,`${e.from} to ${e.to}, traversed ${e.relation}`))}
    {available.map((to,i)=>line(current,to,`a-${i}`,`edge semantic relation-${available.relation||'active'}`,`${current} to ${to}, available semantic path`))}
    {narrative.map((e,i)=>line(e.from,e.to,`n-${i}`,`edge narrative ${e.active?'active':''}`,`${e.from} to ${e.to}, narrative connection`))}
  </svg>;
}

function StableNode({ word, children, className='' }) { const c=COORDS[word]||{x:50,y:50}; return <div className={`stable-node ${className}`} data-word={word} data-x={c.x} data-y={c.y} style={{left:`${c.x}%`,top:`${c.y}%`}}>{children}</div>; }

function Header({ mode, navigate, onReset, paused }) {
  const showNav=!['intro','anchors','final'].includes(mode);
  return <header><div className="brand"><span className="brandmark">✦</span><div><b>词语奥德赛</b><small>WORD ODYSSEY</small></div></div><div className="chapter"><span>{paused?'故事已暂停 · Story paused':'第一章 · CHAPTER I'}</span><b>雾林谜踪</b></div><nav>{showNav&&<><button className={mode==='adventure'?'active':''} onClick={()=>navigate('adventure')}><Compass/> 探索</button><button className={mode==='map'?'active':''} onClick={()=>navigate('map')}><Map/> 地图</button></>}<button className="icon-btn" onClick={onReset} aria-label="Restart"><RotateCcw/></button></nav></header>;
}

function Intro({ onBegin }) {
  const [word,setWord]=useState(null),[theme,setTheme]=useState(null);
  return <main className="intro"><div className="moon"/><section className="intro-copy"><span className="eyebrow">A CHINESE WORD ADVENTURE</span><h1>雾里有一条路，<br/>正等你来发现。</h1><p>Choose a word. Choose a world. The forest will remember every path you take.</p></section><section className="start-panel"><div className="step-label"><span>01</span><div><b>选择一个起点</b><small>Choose your starting word</small></div></div><div className="starter-grid">{starters.map(s=><button key={s[0]} disabled={!s[4]} className={word===s[0]?'selected':''} onClick={()=>setWord(s[0])}><i>{s[3]}</i><strong>{s[0]}</strong><span>{s[1]}</span><small>{s[2]}</small>{!s[4]&&<em>后续旅程 · COMING LATER</em>}</button>)}</div><div className="step-label"><span>02</span><div><b>选择故事世界</b><small>Choose your mystery</small></div></div><div className="theme-grid">{themes.map((t,i)=><button key={t[0]} disabled={!t[2]} className={`${theme===t[0]?'selected':''} theme-${i}`} onClick={()=>setTheme(t[0])}><span className="theme-art">{i===0?'♜':i===1?'◌':'▥'}</span><b>{t[0]}</b><small>{t[1]}</small>{!t[2]&&<em>COMING LATER</em>}</button>)}</div><button className="begin" disabled={!word||!theme} onClick={()=>onBegin({word,theme})}>进入森林 <ChevronRight/><small>ENTER THE FOREST</small></button></section></main>;
}

function RelationBar({ selected, onSelect, current }) { return <div className="relation-wrap"><span className="hint">选择一条词语路径 <i>Choose a relationship</i></span><div className="relations">{Object.entries(RELATIONS).map(([key,label])=><button key={key} className={`${key} ${selected===key?'selected':''}`} disabled={!candidates(current,key).length} onClick={()=>onSelect(key)}><span className="relation-glyph">{key==='similar'?'≈':key==='opposite'?'↔':key==='related'?'⌁':'+'}</span><b>{label[0]}</b><small>{label[1]}</small></button>)}</div></div>; }

function Adventure({ current,visited,seen,relation,history,onRelation,onMove,hasMapRegion,openPortal,paused,resume }) {
  const available=candidates(current,relation); available.relation=relation;
  const visible=[...new Set([...visited,...seen,...available,current])].filter(w=>COORDS[w]);
  return <main className="world adventure stable-world"><div className="mist mist-a"/><div className="mist mist-b"/><div className="forest-silhouette"/><div className="region-label"><span>{COORDS[current]?.region==='story'?'故事中的词':COORDS[current]?.region==='map'?'迷雾地图':'勇气之径'}</span><small>THE FOREST REMEMBERS</small></div><EdgeLayer history={history} available={available} current={current}/>{visible.map(word=>{const status=word===current?'current':available.includes(word)?'available':visited.includes(word)?'visited':'seen';return <StableNode key={word} word={word} className={status==='current'?'is-current':''}><WordNode word={word} status={status} compact={status!=='current'&&status!=='available'} onClick={status==='available'?()=>onMove(word):undefined}/>{status==='current'&&<span className="stable-here">你在这里 · YOU ARE HERE</span>}</StableNode>})}{!relation&&<div className="choose-path-arrow">选择下方的一条路径 <span>↓</span></div>}{paused&&<button className="resume-float" onClick={resume}><Play fill="currentColor"/> 继续故事 <small>RESUME</small></button>}{!hasMapRegion&&current==='胆怯'&&<div className="portals"><span>新的远方正在出现 · A NEW REGION</span><button className="recommended" onClick={openPortal}><i>⌁</i><b>地图</b><small>Map</small></button><button disabled><i>✧</i><b>罗盘</b><small>Coming later</small></button><button disabled><i>▦</i><b>密码</b><small>Coming later</small></button></div>}<RelationBar current={current} selected={relation} onSelect={onRelation}/></main>;
}

function MapView({ visited,seen,hasMapRegion,onReturn,onPreview,preview,onStartStory,anchors,history,paused,resume,final=false,narrative=[],decision }) {
  const allowed=new Set([...courageRegion,...(hasMapRegion?mapRegion:[]),...(final?['雾','低语','石桥','耳语','罗盘','信','脚印']:[])]); const visible=[...new Set([...visited,...seen,...anchors,...narrative.flatMap(e=>[e.from,e.to])])].filter(w=>allowed.has(w)&&COORDS[w]);
  return <main className={`world map-view stable-world ${final?'final-map':''}`}><div className="map-title"><span>{final?'你的旅程仍在继续':'已发现的森林'}</span><small>{final?'YOUR ODYSSEY CONTINUES':'YOUR REVEALED FOREST'}</small></div><div className="region-orb region-courage"><label>勇气之径 <small>COURAGE REGION</small></label></div>{hasMapRegion&&<div className="region-orb region-map"><label>迷雾地图 <small>MAP REGION</small></label></div>}<EdgeLayer history={history} narrative={narrative}/>{visible.map(word=>{const isVisited=visited.includes(word),isSeen=seen.includes(word)&&!isVisited,isStory=narrative.some(e=>e.from===word||e.to===word);return <StableNode key={word} word={word}><WordNode word={word} compact status={isVisited?'visited':isSeen?'seen':'inactive'} anchor={anchors.includes(word)} story={final&&isStory} onClick={!final?(isVisited?()=>onReturn(word):isSeen?()=>onPreview(word):undefined):undefined}/></StableNode>})}<div className="map-legend"><span><i className="line semantic"/> Semantic</span><span><i className="line traversed"/> Traversed</span><span><i className="line narrative"/> Narrative</span></div>{!final&&hasMapRegion&&visited.includes('神秘线索')&&<button className="story-ready" onClick={onStartStory}><Sparkles/> 选择故事星词 <small>CHOOSE STORY STARS</small></button>}{paused&&<button className="resume-float" onClick={resume}><Play fill="currentColor"/> 继续故事 <small>RESUME</small></button>}{preview&&<div className="preview-card"><Eye/><div><b>{preview} <em>{WORDS[preview][0]}</em></b><span>{WORDS[preview][1]}</span><p>你在“英勇”的近义词中见过它。<br/>You saw it among words similar to 英勇.</p></div><button onClick={()=>onPreview(null)}>×</button></div>}{final&&<div className="final-card"><Sparkles/><div><b>{decision}</b><span>{visited.length} 个词语 · 2 个区域 · {history.length} 段语义旅程</span></div></div>}</main>;
}

function AnchorSelect({ onConfirm }) { const [selected,setSelected]=useState([]),[avatar,setAvatar]=useState(null); const toggle=w=>setSelected(s=>s.includes(w)?s.filter(x=>x!==w):s.length<2?[...s,w]:s); return <main className="anchor-screen"><div className="anchor-head"><span className="eyebrow">BUILD YOUR STORY</span><h2>选择两个故事星词</h2><p>Any two selected words and explorer will appear in the story.</p></div><div className="constellation"><div className="anchor-region"><label>勇气之径</label>{courageAnchors.map(w=><WordNode key={w} word={w} status={selected.includes(w)?'available':'visited'} anchor={selected.includes(w)} onClick={()=>toggle(w)}/>)}</div><div className="anchor-region"><label>迷雾地图</label>{mapAnchors.map(w=><WordNode key={w} word={w} status={selected.includes(w)?'available':'visited'} anchor={selected.includes(w)} onClick={()=>toggle(w)}/>)}</div></div><section className="avatar-tray"><div><b>谁来探索？</b><small>Choose a preset explorer</small></div>{[['凯','KAI','◒'],['岚','LAN','◓'],['诺','NUO','◑']].map(a=><button key={a[0]} className={avatar===a[0]?'selected':''} onClick={()=>setAvatar(a[0])}><i>{a[2]}</i><b>{a[0]}</b><small>{a[1]}</small></button>)}</section><button className="begin-story" disabled={selected.length!==2||!avatar} onClick={()=>onConfirm(selected,avatar)}><Sparkles/> 开始故事 <small>BEGIN THE STORY</small></button></main>; }

function StoryView({ beat,setBeat,anchors,avatar,ingredient,setIngredient,onPauseWord,onPause,onFinish }) {
  const [help,setHelp]=useState(false),[toolbox,setToolbox]=useState(false),[pending,setPending]=useState(null); const content=storyBeat({beat,anchors,avatar,ingredient}); const narrative=content.words.slice(0,-1).map((w,i)=>({from:w,to:content.words[i+1],active:true}));
  return <main className="world story-view stable-world"><div className="night-vignette"/><div className="story-kicker"><span>故事正在连接你的词语</span><small>YOUR WORDS ARE LIGHTING THE FOREST</small></div><EdgeLayer narrative={narrative}/>{content.words.map(word=><StableNode key={word} word={word}><WordNode word={word} story anchor={anchors.includes(word)} onClick={word==='低语'?onPauseWord:undefined}/></StableNode>)}<section className="story-panel"><span className="beat-count">故事片段 {beat+1} · STORY BEAT</span><p>{content.zh}</p>{help&&<div className="translation">{content.en}</div>}<div className="story-actions"><button onClick={()=>setHelp(!help)}><HelpCircle/> English help</button>{beat<2&&<button className="primary" onClick={()=>setBeat(beat+1)}>继续 <ChevronRight/></button>}{beat===2&&<button className="primary" onClick={()=>setToolbox(true)}><Sparkles/> 加入意外</button>}</div></section>{toolbox&&beat===2&&<div className="toolbox"><div className="tool-head"><div><b>加入意外</b><small>ADD A SURPRISE</small></div><button onClick={()=>setToolbox(false)}>×</button></div><p>What should {avatar} discover near the bridge?</p><div className="ingredient-grid">{[['发光的罗盘','a glowing compass','✧'],['藏起来的信','a hidden letter','▱'],['蓝色脚印','blue footprints','⌁']].map(x=><button key={x[0]} className={pending===x[0]?'selected':''} onClick={()=>setPending(x[0])}><i>{x[2]}</i><b>{x[0]}</b><small>{x[1]}</small></button>)}</div><button className="confirm-choice" disabled={!pending} onClick={()=>{setIngredient(pending);setToolbox(false);setBeat(3)}}>让它出现 <Sparkles/></button></div>}{beat===3&&<div className="next-choice"><span>{avatar}下一步应该做什么？</span>{Object.keys(DIRECTOR_OUTCOMES).map(x=><button key={x} onClick={()=>onFinish(x)}>{x}<small>{x==='跟着蓝光'?'Follow the light':x==='检查地图'?'Check the map':'Find the speaker'}</small></button>)}</div>}<button className="pause-story" onClick={onPause}><Pause/> 暂停</button></main>;
}

export default function App(){
  const [mode,setMode]=useState('intro'),[current,setCurrent]=useState('勇敢'),[visited,setVisited]=useState([]),[seen,setSeen]=useState([]),[relation,setRelation]=useState(null),[history,setHistory]=useState([]),[hasMapRegion,setHasMapRegion]=useState(false),[preview,setPreview]=useState(null),[anchors,setAnchors]=useState([]),[avatar,setAvatar]=useState('凯'),[paused,setPaused]=useState(false),[resumeBeat,setResumeBeat]=useState(0),[beat,setBeat]=useState(0),[ingredient,setIngredient]=useState('发光的罗盘'),[decision,setDecision]=useState('');
  const available=useMemo(()=>candidates(current,relation),[current,relation]); const reset=()=>{setMode('intro');setCurrent('勇敢');setVisited([]);setSeen([]);setRelation(null);setHistory([]);setHasMapRegion(false);setPreview(null);setAnchors([]);setAvatar('凯');setPaused(false);setResumeBeat(0);setBeat(0);setIngredient('发光的罗盘');setDecision('')};
  const begin=({word})=>{setCurrent(word);setVisited([word]);setMode('adventure')}; const selectRelation=r=>{setRelation(r);setSeen(s=>[...new Set([...s,...candidates(current,r)])])}; const move=w=>{if(!available.includes(w))return;setHistory(h=>recordTraversal(h,current,w,relation,paused?'story-pause':'explore'));setVisited(v=>[...new Set([...v,current,w])]);setCurrent(w);setRelation(null)};
  const openPortal=()=>{setHasMapRegion(true);setVisited(v=>[...new Set([...v,'地图'])]);setCurrent('地图');setRelation(null)}; const pauseTo=(target,targetBeat=beat)=>{setPaused(true);setResumeBeat(targetBeat);setMode(target)}; const pauseWord=()=>{setVisited(v=>[...new Set([...v,'低语'])]);setCurrent('低语');setRelation(null);pauseTo('adventure',2)}; const resume=()=>{const next=resumeState({resumeBeat});setPaused(next.paused);setBeat(next.beat);setMode('story')}; const navigate=target=>{if(mode==='story')pauseTo(target,beat);else setMode(target)};
  const narrative=[{from:anchors[0]||'勇敢',to:'雾'},{from:'雾',to:'低语'},{from:'低语',to:'石桥'},{from:'低语',to:'耳语'},{from:'石桥',to:ingredient==='藏起来的信'?'信':ingredient==='蓝色脚印'?'脚印':'罗盘'},{from:ingredient==='藏起来的信'?'信':ingredient==='蓝色脚印'?'脚印':'罗盘',to:anchors[1]||'神秘线索'}];
  return <div className={`app mode-${mode}`}><Header {...{mode,navigate,paused}} onReset={reset}/>{mode==='intro'&&<Intro onBegin={begin}/>} {mode==='adventure'&&<Adventure {...{current,visited,seen,relation,history,hasMapRegion,paused}} onRelation={selectRelation} onMove={move} openPortal={openPortal} resume={resume}/>} {mode==='map'&&<MapView {...{visited,seen,hasMapRegion,preview,anchors,history,paused}} onReturn={w=>{setCurrent(w);setRelation(null);setMode('adventure')}} onPreview={setPreview} onStartStory={()=>setMode('anchors')} resume={resume}/>} {mode==='anchors'&&<AnchorSelect onConfirm={(a,v)=>{setAnchors(a);setAvatar(v);setBeat(0);setMode('story')}}/>} {mode==='story'&&<StoryView {...{beat,setBeat,anchors,avatar,ingredient,setIngredient}} onPauseWord={pauseWord} onPause={()=>pauseTo('adventure',beat)} onFinish={choice=>{setDecision(DIRECTOR_OUTCOMES[choice].replace('凯',avatar));setMode('final')}}/>} {mode==='final'&&<MapView final hasMapRegion visited={[...new Set([...visited,'耳语'])]} seen={seen} anchors={anchors} history={history} narrative={narrative} decision={decision} onPreview={()=>{}} onReturn={()=>{}}/>}</div>;
}
